### ISSUE TITLE
Class `PHPUnit_Framework_Error` does not exist

### ISSUE THREAD

**Issue by AlbinoDrought** [sebastianbergmann/phpunit-documentation#447] opened 2017-07-14 17:10 UTC
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | PHPUnit 6.2.3 by Sebastian Bergmann and contributors.
| PHP version         | PHP 7.0.18-0ubuntu0.16.04.1 (cli) ( NTS )
| Installation Method | Composer

Issue:

The classes, `PHPUnit_Framework_Error`, `PHPUnit_Framework_Error_Notice`, and `PHPUnit_Framework_Error_Warning` seem to have been superseded by `PHPUnit\Framework\Error\Error`, `PHPUnit\Framework\Error\Notice`, and `PHPUnit\Framework\Error\Warning`, but this change is not reflected in the docs (unless I'm dumb and am reading the wrong version - wouldn't be the first time)

---

Hello,

While attempting to test for an expected warning, triggered using `trigger_error($message, E_USER_WARNING);`, I was unable to find the class specified in the docs.

Here is the exact url I was reading: 
>https://phpunit.de/manual/current/en/writing-tests-for-phpunit.html#writing-tests-for-phpunit.exceptions

Given example: 
>Example 2.12: Expecting a PHP error using @expectedException

```
<?php
use PHPUnit\Framework\TestCase;

class ExpectedErrorTest extends TestCase
{
    /**
     * @expectedException PHPUnit_Framework_Error
     */
    public function testFailingInclude()
    {
        include 'not_existing_file.php';
    }
}
?>
```

Below this:

>PHPUnit_Framework_Error_Notice and PHPUnit_Framework_Error_Warning represent PHP notices and warnings, respectively.

While doing my best at sleuthing, I discovered the thrown error was actually `PHPUnit\Framework\Error\Warning`, and the class `PHPUnit_Framework_Error_Warning` (or `PHPUnit_Framework_Error*), don't exist locally. 

Here is my special sleuthing code:

```
try {
    // trigger warning here
} catch (\Exception $ex) {
    print_r(get_class($ex));
    die();
}
```

**Comment by sebastianbergmann** [comment] 2017-07-15 02:54
Duplicate of #446.

**Closed by sebastianbergmann** 2017-07-15 02:54 UTC
